name: CDK Deployment

on:
  push:
    branches:
      - main  # Adjust this to the appropriate branch name

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          if [ ! -d "/usr/local/aws-cli/v2/current" ]; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          fi
          aws --version

      - name: Install AWS CDK
        run: npm install -g aws-cdk@2.62.2
        env:
          # If using Node.js 14 in GitHub Actions
          NODE_OPTIONS: --openssl-legacy-provider

      - name: CDK Deploy
        run: |
          cd bilenivar_infra
          cdk deploy BilenivarInfraStack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
